# -*- coding: utf-8 -*-
"""lecture4_name

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PoaUEThOVBjYJUWqF5EyC1Igf4ZoZPL3
"""



"""first program"""

print(12)

"""factorial"""

n=5
fact=1
for i in range(1,n+1):
  fact = fact*i
print(fact)



"""fibbonaci

"""

n=10
a=0
b=1
for i in range(n):
  print(a,end=" ")
  next_value=a+b
  a=b
  b=next_value



"""struct to dict

"""